trigger:
- main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: region
    type: string
    default: 'ap-south-1'

steps:
- checkout: self

- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.6.6'

- script: |
    echo "🔧 Region passed: ${{ parameters.region }}"
    terraform init
    terraform plan -var="aws_region=${{ parameters.region }}" -var-file="terraform.tfvars.json"
    terraform apply -auto-approve -var="aws_region=${{ parameters.region }}" -var-file="terraform.tfvars.json"
  displayName: 'Terraform Apply with Region'

